### PR TITLE
cpp: Emit Bit Position

### PR DESCRIPTION
**Pull request by johannes-wolf**
**Please check [contribution guide](https://github.com/ndsev/zserio/CONTRIBUTING.md) first.**

# Description

This PR adds a new flag to the C++ emitter: `-withSourceRegion` (unset by default).
If enabled, this adds a new `getSourceRegion -> tuple<size_t, size_t>` function to compound types that returns the bit-position (and size) of the object in the buffer (if deserialized), or 0 if the object was not read from a blob.

To improve and simplify the template code for C++ initializer list, a new utility function `compiler/extensions/cpp/freemarker/CppUtility.inc.ftl` got added that helps to get rid of some noisy `<#if>`'s in the FTL code. No verbose checks for adding `:` or `,` needed any more.

# Type of Change

* [ ] Bug fix
* [x] New feature
* [ ] Documentation enhancement

# ToDo

- [x] Rename `getSourceRegion()` to `bitPosition()`
- [x] Return a single `size_t` instead of an offset+length tuple

### CODE REVIEW

**Comment by johannes-wolf** [comment]
SonarCloud is not working for all my PRs because of some configuration problem I guess.

**Comment by mikir** [comment]
> SonarCloud is not working for all my PRs because of some configuration problem, I guess.

Yes, this is because currently SonarCloud does not support forked repositories directly. There is some workaround but we did not have enough time to check it. We will boost this issue up because bigger changes in C++ can potentionaly introduce some new SonarCloud findings.

**Comment by mikir** [comment]
> This PR adds a new flag to the C++ emitter: `-withSourceRegion` (unset by default).
> If enabled, this adds a new `getSourceRegion -> tuple<size_t, size_t>` function to compound types that returns the bit-position (and size) of the object in the buffer (if deserialized), or 0 if the object was not read from a blob.

We will discuss about the solution of this problem internally as soon as we are both in work (vacation). But in the meantime, I have three remarks:

1. I guess you have already considered this but I would like to ask if is there any theoretical possibility to calculate bit position directly in your application? Something like calling `bitSizeOf()` method from the top level Zserio object? The main reason why I am asking this is that I have recently got a lot of complains because of over complicated Zserio generator interface (two many command line options which influence generated code). These complains actually suggest to simplify this as much as possible. And this solution would make things even worse.
2. We should avoid in the generated API to have two different ways how to get the same information. Bit size can be already read using the `bitSizeOf()` method, therefore returning the same thing by the different method should be avoided.
3. Because this is a new feature request and not a minor fix, please create a corresponding issue where we can discuss about the solution. Thanks!

**Comment by johannes-wolf** [comment]
> > This PR adds a new flag to the C++ emitter: `-withSourceRegion` (unset by default).
> > If enabled, this adds a new `getSourceRegion -> tuple<size_t, size_t>` function to compound types that returns the bit-position (and size) of the object in the buffer (if deserialized), or 0 if the object was not read from a blob.
> 
> We will discuss about the solution of this problem internally as soon as we are both in work (vacation). But in the meantime, I have three remarks:
> 
>     1. I guess you have already considered this but I would like to ask if is there any theoretical possibility to calculate bit position directly in your application? Something like calling `bitSizeOf()` method from the top level Zserio object? The main reason why I am asking this is that I have recently got a lot of complains because of over complicated Zserio generator interface (two many command line options which influence generated code). These complains actually suggest to simplify this as much as possible. And this solution would make things even worse.

See linked issue #652.

>     2. We should avoid in the generated API to have two different ways how to get the same information. Bit size can be already read using the `bitSizeOf()` method, therefore returning the same thing by the different method should be avoided.

I will change `getSourceRegion` to `getSourcePosition` returning a single `size_t`.
 
>     3. Because this is a new feature request and not a minor fix, please create a corresponding issue where we can discuss about the solution. Thanks!

I have created a new issue #652.

**Comment by mikir** [comment]
Thanks a lot for a new issue and quick reaction.

> I will change `getSourceRegion` to `getSourcePosition` returning a single `size_t`.

One small note regarding naming, `getSourcePosition` can clash with the getter of the field named as `sourcePosition`. I would suggest to rename it, e.g. to `bitPosition()` with command line option `-withBitPosition`. Or something similar.

**Comment by johannes-wolf** [comment]
@mikir I've added some simple unit tests and had to regenerate all the `test_object` sources, which makes the PR somewhat noisy. Those changes are in commit [7cd0809](https://github.com/ndsev/zserio/pull/648/commits/7cd0809b1c6bfabc512fd5a3b46cfef149b38829). Why don't we generate those zserio sources as part of the build and remove them from the repo?

**Comment by mikir** [comment]
> @mikir I've added some simple unit tests and had to regenerate all the `test_object` sources, which makes the PR somewhat noisy. Those changes are in commit [7cd0809](https://github.com/ndsev/zserio/pull/648/commits/7cd0809b1c6bfabc512fd5a3b46cfef149b38829). Why don't we generate those zserio sources as part of the build and remove them from the repo?

`test_object` sources are not intended for the generator testing. They are intended only for the runtime library testing. And the runtime library had to be developed before the generator, so there was no way how to generate them automatically. The generator tests are located in the `test` directory. For this use case, it would be necessary to create a special test in `test\arguments\with_bitposition_code` with a new sample schema. Of course, I can explain it in much more details what is necessary to do.

I really appreciate your effort but before we move further with testing, I would suggest to double check that this solution is a good solution. Unfortunately, I don't have time this week to pay too much attention to this new feature but I can see two drawbacks of this solution so far:

1. Memory consumption
  This won't be probably a big problem but it would good to have some better understanding of this to be prepared. Because it is already implemented, it would be very helpful to check the memory consumption for real data. For example using some huge NDS.Live blob. Ideally, to have some numbers. Do you think that it would be possible to check it on your side?
2. Easy misuse of the `bitposition` method
  I like the simplicity of this solution but this design is suitable only for immutable objects (only if `-withoutWriterCode` is applied). Correct me if I am wrong but this is not that case. Therefore, I can imagine the following easy misuse:

    - Application will call read constructor of the top level zserio object which fills correctly all bit positions.
    - Then, application will call some field setter on the top level zserio object which will change encoding not only of the top level object but of all nested Zserio object as well (e.g. if this field is used in optional if clause).
    - Nobody will be aware of this situation and all `bitPosition` calls will return non-zero number which will be invalid.
    - It would be good at least to throw exception in this case but it is quite complicated to detect all such changes.

    I would say that we should think a little bit more about usage not to introduce some easy confusions for users.

**Comment by johannes-wolf** [comment]
Thank you. I've removed the `test_object` test and added a new `/test/arguments/with_bit_position` test case.

Regarding memory consumption: Since this feature is optional and disabled by default, I do not see this being a problem and I have no idea of how to optimize this with the way zserio is build & generates code. But I've not yet done any measurements/comparisons, nor have I tested it with huge blobs.

**Comment by mikir** [comment]
Thanks for your effort.

I just would like to suggest to rename the option `-withBitPosition` to `-withBitPositionCode` to be consistent with other options like `-withRangeCheckCode`, `-withSqlCode`, etc... Is it OK?

There is no action required from your side, I am planning to create a new branch accepting this PR and rename this option and continue (e.g. with documentation).

**Comment by johannes-wolf** [comment]
> Thanks for your effort.
> 
> I just would like to suggest to rename the option `-withBitPosition` to `-withBitPositionCode` to be consistent with other options like `-withRangeCheckCode`, `-withSqlCode`, etc... Is it OK?

OK :+1:.

**Comment by mikir** [comment]
Thanks for renaming, I will continue on the branch.

**Pull request merged**
